from django.urls import path
from .views import (render_see_allFeedbacks,
    get_caloric_intake,
    get_user_measurements,
    get_user_reminders,
    get_workout_data,
    login,
    adminlogin,
    render_see_allFeedbacks,
    userpage,
    exercises,
    food,
    delete_item,
    edit_food,
    edit_user,
    view_profile,
    dashboard,
    add_new_user,
    register_new_user,
    alter_user_details,
    navigate_to_add_exercise,
    navigate_to_add_food,
    add_new_exercise,
    add_new_food,
    delete_exercise,
    navigate_to_send_email,
    render_push_notificatoin,
    naviagte_to_send_all_email,
    delete_user,
    navigate_to_user_view_options,
    render_edit_page,
    render_edit_exercise_page,
    edit_exercise,
    render_please_login,
    render_subscription_page,
    
)
from .graphs import generate_bar_chart
from users.email import send_special_offers, send_mail_to_all_users

urlpatterns = [
    path("edit_exercise/<int:item_id>", edit_exercise, name="edit_exercise"),
    path(
        "render_exercise_edit_page/<int:item_id>",
        render_edit_exercise_page,
        name="render_exercise_edit_page",
    ),
    path("see_all_feedbacks/", render_see_allFeedbacks, name="see_all_feedbacks"),
    path("login/", login, name="custom_login"),
    path("performlogin/", adminlogin, name="performlogin"),
    path("users/", userpage, name="users"),
    path("exercises/", exercises, name="exercises"),
    path("food/", food, name="food"),
    path("render_edit_page/<int:item_id>", render_edit_page, name="render_edit_page"),
    path("delete_item/<int:item_id>/", delete_item, name="delete_item"),
    path("delete_user/<int:user_id>/", delete_user, name="delete_user"),
    path("edit_food/<int:item_id>/", edit_food, name="edit_food"),
    path("edituser/<int:user_id>/", edit_user, name="edit_user"),
    path("viewprofile/<int:user_id>", view_profile, name="view_profile"),
    path("dashboard/", dashboard, name="dashboard"),
    path("adduser/", add_new_user, name="add_new_user"),
    path("registeruser/", register_new_user, name="register_new_user"),
    path("alteruser/<str:username>/", alter_user_details, name="alter_user_details"),
    path(
        "navigate_to_add_exercise/",
        navigate_to_add_exercise,
        name="navigate_to_add_exercise",
    ),
    path("navigate_to_add_food/", navigate_to_add_food, name="navigate_to_add_food"),
    path("add_new_exercise/", add_new_exercise, name="add_new_exercise"),
    path("add_new_food/", add_new_food, name="add_new_food"),
    path("deleteexercise/<int:exercise_id>/", delete_exercise, name="delete_exercise"),
    path("sendoffermail/<str:email>/", send_special_offers, name="send_offer_mail"),
    path(
        "navigate_to_send_email/", navigate_to_send_email, name="navigate_to_send_email"
    ),
    path(
        "naviagte_to_send_all_email/",
        naviagte_to_send_all_email,
        name="naviagte_to_send_all_email",
    ),
    path("sendemailtoall/", send_mail_to_all_users, name="send_mail_to_all_users"),
    path(
        "navigate_to_user_view_options/<int:id>/",
        navigate_to_user_view_options,
        name="navigate_to_user_view_options",
    ),
    path("get_caloric_intake/<int:id>", get_caloric_intake, name="get_caloric_intake"),
    path("get_workout_data/<int:id>", get_workout_data, name="get_workout_data"),
    path(
        "get_user_measurements/<int:id>",
        get_user_measurements,
        name="get_user_measurements",
    ),
    path("get_user_reminders/<int:id>", get_user_reminders, name="get_user_reminders"),
    path("generate_bar_chart/", generate_bar_chart, name="generate_bar_chart"),
    path("render_please_login/", render_please_login, name="render_please_login"),
    path(
        "render_subscription_page/",
        render_subscription_page,
        name="render_subscription_page",
    ),
    path(
        "render_push_notificatoin/",
        render_push_notificatoin,
        name="render_push_notificatoin",
    ),
]
