# Generated by Django 4.2.3 on 2024-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloricintake', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caloricintake',
            constraint=models.UniqueConstraint(fields=('username', 'timestamp'), name='composite_primary_key'),
        ),
    ]
