# Generated by Django 4.2.3 on 2024-02-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0002_exercise_calories_burned_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('routine_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or comments', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.exercise')),
            ],
            options={
                'verbose_name': 'Workout Routine',
                'verbose_name_plural': 'Workout Routines',
            },
        ),
    ]
