# Generated by Django 5.0.1 on 2024-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='Food Item', max_length=100)),
                ('food_image', models.ImageField(blank=True, upload_to='images/')),
                ('food_description', models.CharField(default='Food Description', max_length=1000)),
                ('food_calories_per_serving', models.FloatField(default=0.0)),
                ('food_serving_size', models.FloatField(default=0.0)),
                ('food_protein_per_serving', models.FloatField(default=0.0)),
                ('food_carbs_per_serving', models.FloatField(default=0.0)),
                ('food_fat_per_serving', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'food_food',
            },
        ),
    ]
