# Generated by Django 5.0.1 on 2024-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
