# Generated by Django 4.2.3 on 2024-02-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='added_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
