# Generated by Django 4.2.3 on 2024-03-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_added_by_user_food_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_protein_per_serving',
        ),
    ]
