# Generated by Django 4.2.3 on 2024-03-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_food_food_protein_per_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_protein_per_servings',
            field=models.FloatField(default=0.0),
        ),
    ]
