# Generated by Django 4.2.3 on 2024-01-29 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('measurement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('chest_size', models.FloatField(help_text='Chest size in centimeters')),
                ('waist_size', models.FloatField(help_text='Waist size in centimeters')),
                ('hip_size', models.FloatField(help_text='Hip size in centimeters')),
                ('left_arm', models.FloatField(help_text='Left arm size in centimeters')),
                ('right_arm', models.FloatField(help_text='Right arm size in centimeters')),
                ('left_leg', models.FloatField(help_text='Left leg size in centimeters')),
                ('right_leg', models.FloatField(help_text='Right leg size in centimeters')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
