# Generated by Django 4.2.3 on 2024-02-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmeasurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='left_leg',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='right_leg',
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_calf',
            field=models.FloatField(default=0, help_text='Left calf size in inches'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_forearm',
            field=models.FloatField(default=0, help_text='Left forearm size in inches'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_quadricep',
            field=models.FloatField(default=0, help_text='Left quadricep size in inches'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_calf',
            field=models.FloatField(default=0, help_text='Right calf size in inches'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_forearm',
            field=models.FloatField(default=0, help_text='Right forearm size in inches'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_quadricep',
            field=models.FloatField(default=0, help_text='Right quadricep size in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='chest_size',
            field=models.FloatField(default=0, help_text='Chest size in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='height',
            field=models.FloatField(default=0, help_text='Height in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='hip_size',
            field=models.FloatField(default=0, help_text='Hip size in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='left_arm',
            field=models.FloatField(default=0, help_text='Left arm size in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or comments', null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='right_arm',
            field=models.FloatField(default=0, help_text='Right arm size in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='waist_size',
            field=models.FloatField(default=0, help_text='Waist size in inches'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='weight',
            field=models.FloatField(default=0, help_text='Weight in kilograms'),
        ),
    ]
