# Generated by Django 5.0.1 on 2024-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetBodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_details', models.CharField(max_length=100)),
                ('exercise_image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('target_body_part', models.ManyToManyField(to='exercise.targetbodypart')),
            ],
        ),
    ]
