# Generated by Django 5.0.1 on 2024-01-28 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TargetBodyPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_details', models.TextField()),
                ('exercise_image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercisetype')),
                ('target_body_part', models.ManyToManyField(to='exercise.targetbodypart')),
            ],
        ),
    ]
