# Generated by Django 4.2.3 on 2024-02-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_burned_per_hour',
            field=models.IntegerField(default=100),
        ),
    ]
