# Generated by Django 4.2.3 on 2024-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_calories_burned_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='added_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
