# Generated by Django 5.0.1 on 2024-02-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exercise_added_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
