# Generated by Django 4.2.3 on 2024-02-24 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(default='Meal Item', max_length=100)),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
                ('meal_description', models.CharField(default='Meal Description', max_length=1000)),
                ('meal_calories', models.FloatField(default=0.0)),
                ('meal_protein', models.FloatField(default=0.0)),
                ('meal_carbs', models.FloatField(default=0.0)),
                ('meal_fat', models.FloatField(default=0.0)),
                ('added_by_user', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_meal',
            },
        ),
    ]
