# Generated by Django 5.0.1 on 2024-04-20 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0006_food_food_protein_per_servings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_mealplan',
            },
        ),
        migrations.CreateModel(
            name='MealPlanFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.FloatField(default=1.0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custommeal.mealplan')),
            ],
            options={
                'db_table': 'food_mealplanfood',
            },
        ),
        migrations.AddField(
            model_name='mealplan',
            name='foods',
            field=models.ManyToManyField(through='custommeal.MealPlanFood', to='food.food'),
        ),
    ]
