# Generated by Django 5.0.1 on 2024-04-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custommeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='day',
        ),
    ]
