# Generated by Django 4.2.3 on 2024-02-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
