# Generated by Django 4.2.3 on 2024-02-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_gender_customuser_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_custom_routines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_customexercises',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_customfood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_custommeals',
            field=models.IntegerField(default=0),
        ),
    ]
