# Generated by Django 4.2.3 on 2024-02-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_number_of_custom_routines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recommended_calories',
            field=models.FloatField(default=0),
        ),
    ]
