# Generated by Django 5.0.1 on 2024-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_subscription_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', '6 Monthly'), ('3', 'Yearly')], max_length=20),
        ),
    ]
